"""Add is_in_library field to workflows table

Revision ID: add_is_in_library_field
Revises: 91e5166dcf37
Create Date: 2026-05-19 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_is_in_library_field'
down_revision: Union[str, None] = '91e5166dcf37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('is_in_library', sa.Boolean(), nullable=True, default=False))
    # 设置默认值为 False
    op.execute('UPDATE workflows SET is_in_library = FALSE WHERE is_in_library IS NULL')
    # 设置字段为 NOT NULL
    op.alter_column('workflows', 'is_in_library', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'is_in_library')
    # ### end Alembic commands ###
